echo "**File Path:** \`apps/web/src/app/(dashboard)/backlog/actions.ts\`"
echo "**Violated Boundary/Rule:** \`Enforce that all client-side form submissions and data payloads sent to the API are validated using Zod schemas imported from the @sprintpulse shared workspace. Flag any hardcoded or local validation logic that bypasses the shared schemas.\`"
echo ""
echo "**Failing Code Snippet:**"
echo "\`\`\`typescript"
echo "  const title = formData.get('title') as string"
echo "  const type = formData.get('type') as string"
echo "  const points = parseInt(formData.get('points') as string || '0', 10)"
echo "  const teamId = formData.get('teamId') as string"
echo "  const accountId = formData.get('accountId') as string"
echo ""
echo "  if (!title) return { error: 'Title is required' }"
echo "\`\`\`"
echo ""
echo "**Required Correction:** \`Import the appropriate Zod schema from @sprintpulse/shared and use it to validate the FormData instead of manually extracting and checking fields.\`"
